services:
  # 1. Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: smartcat_db
    restart: always
    environment:
      POSTGRES_USER: smartcat_user
      POSTGRES_PASSWORD: smartcat_password
      POSTGRES_DB: smartcat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Broker MQTT Local (Para testes sem depender de internet)
  broker:
    image: eclipse-mosquitto:2
    container_name: smartcat_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # 3. Backend Python (FastAPI + Worker MQTT + APScheduler)
  web:
      build:
        context: ../backend
        dockerfile: Dockerfile
      container_name: smartcat_app
      restart: always
      ports:
        - "8000:8000"
      environment:
        - DATABASE_URL=postgresql://smartcat_user:smartcat_password@db:5432/smartcat_db
        - MQTT_BROKER=broker.hivemq.com
        - MQTT_PORT=1883
      volumes:
        - ../backend:/app
      depends_on:
      - db
      - broker

volumes:
  postgres_data: